import{a as y,i as d,S as f}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();y.defaults.baseURL="https://pixabay.com/api/";const H="42552421-44c442bdd9fc0080a82eeb482";async function p(e,r,s){return await y.get(`?key=${H}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${s}`)}const P=e=>{const r=document.querySelector(".gallery");e.length===0&&d.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"});const s=e.map(({id:t,largeImageURL:o,webformatURL:a,tags:S,likes:I,views:q,comments:v,downloads:$})=>`
      <a class="gallery__link" href="${o}">
        <div class="gallery-item" id="${t}">
          <img class="gallery-item__img" src="${a}" alt="${S}" loading="lazy" />
          <div class="info">
            <p class="info-item"><b>Likes</b>${I}</p>
            <p class="info-item"><b>Views</b>${q}</p>
            <p class="info-item"><b>Comments</b>${v}</p>
            <p class="info-item"><b>Downloads</b>${$}</p>
          </div>
        </div>
      </a>`).join("");r.insertAdjacentHTML("beforeend",s),new f(".gallery-item",{captionsData:"alt",captionDelay:250}).refresh()},w=document.getElementById("search-form"),l=document.querySelector(".gallery"),n=document.querySelector(".load-more-btn"),g=document.querySelector(".loader");let u="",c=1;const h=15;let b;C();w.addEventListener("submit",E);n.addEventListener("click",D);function L(e){if(g.style.display="none",(e.totalHits===0||e.hits&&e.hits.length===0)&&l.innerHTML.trim()==="")O();else{const s=Math.ceil(e.totalHits/h);c>s||l.querySelectorAll(".gallery-item").length>=e.totalHits?(n.classList.add("is-hidden"),m()):(P(e.hits),b=new f(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),n.classList.remove("is-hidden"),T(M()*2))}}function E(e){if(e.preventDefault(),c=1,u=e.currentTarget.searchQuery.value.trim(),l.innerHTML="",n.classList.add("is-hidden"),u===""){N();return}const r=e.currentTarget.searchQuery;r&&(r.value=""),p(u,c,h).then(({data:s})=>{L(s)}).catch(s=>console.log(s))}function M(){const e=document.querySelector(".gallery-item");return e?e.getBoundingClientRect().height:0}function T(e){window.scrollBy({top:e,behavior:"smooth"})}function C(){l.innerHTML=""}function D(){g.style.display="block",c+=1,b.destroy(),p(u,c,h).then(({data:e})=>{l.querySelectorAll(".gallery-item").length>=e.totalHits?(n.classList.add("is-hidden"),m()):L(e)}).catch(e=>console.log(e)).finally(()=>{g.style.display="none"})}function N(){d.error({title:"Error",message:"The search string cannot be empty. Please specify your search query."})}function m(){d.error({title:"",message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"})}function O(){d.error({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomRight"})}
//# sourceMappingURL=commonHelpers.js.map
